### ISSUE TITLE
linphone-js does not compile

### ISSUE THREAD

**Issue by MichaelDaum** [juzna/linphone-js#1]
Hi,

been trying to install this on ubuntu 10.04. So I pulled firebreath from git and downloaded linphone-js. then proceeded the normal (firebreath) way compiling this plugin. this did not work out with lots of compile errors starting with:

/home/micha/Projekt/browser/firebreath/src/ScriptingCore/BrowserObjectAPI.h:19:2: warning: #warning "This header is deprecated - include JSObject.h instead."
/home/micha/Projekt/browser/projects/linphone/linphoneAPI.cpp:9:35: error: DOM/JSAPI_DOMDocument.h: No such file or directory
In file included from /home/micha/Projekt/browser/projects/linphone/linphoneAPI.cpp:13:
/home/micha/Projekt/browser/projects/linphone/linphoneAPI.h:22:73: error: private.h: No such file or directory
/home/micha/Projekt/browser/projects/linphone/linphoneAPI.h:26:26: error: linphonecore.h: No such file or directory
In file included from /home/micha/Projekt/browser/projects/linphone/linphoneAPI.cpp:13:
/home/micha/Projekt/browser/projects/linphone/linphoneAPI.h:60: warning: ‘BrowserHostWrapper’ is deprecated (declared at /home/micha/Projekt/browser/firebreath/src/ScriptingCore/BrowserHost.h:68)

etc.

It seems linphone-js needs kind of catch up with the latest firebreath.

I then tried cd doc && sh build.sh 

to see if that goes any further. Fails more or less with the same errors as above, with the difference that it uninstalled some core libraries from the system, downloaded another linphone distro from the net and installed it all over the place in /usr/local...

Then compilation broke as well, leaving me behind with a total mess. Took me a while to remove the newly installed stuff from /usr/local.

This all is quite unfortunate as I think that the basic idea of linphone-js is just great ... 

Is this still maintained? I'd love to give it another try and work out something on top.

**Comment by juzna** [comment]
Hi, I haven't been working on this plugin for a while (as you can see in commits). Last time I had Firebreath was even before final release of version 1.0, as I'm looking now it has moved to 1.4 which probably means lots of changes. I'm checking documentation now to see what has changed and to estimate difficult of upgrading linphone-js to new firebreath.
However, the company I was working for, decided not to use this plugin, so the full time development stopped :( But I'll do my best in my spare time to make it work.

**Comment by MichaelDaum** [comment]
Thanks a lot.

**Comment by juzna** [comment]
I have found there have been many changes to FireBreath and many more to Linphone core, so I think I will need to write most of the code from scratch again to make it work :/

**Comment by MichaelDaum** [comment]
No action.
